### ISSUE TITLE
Is it stable enough right now

### ISSUE THREAD

**Issue by emersont1** [Tape-Worm/Gorgon#1]
Is the 2.0 library stable enough to be used in a game dev project, and what are the recommended requirements for running the engine?

**Comment by Tape-Worm** [comment]
Yeah, it should be OK for use. The only thing is that the editor that's included for building sprites and whatnot is not really complete.

You'll need .NET 4.5, and Visual Studio 2013 as a minimum to compile the thing and you'll need Direct3D 11 and Windows 7.
