### ISSUE TITLE
Can not resize window

### ISSUE THREAD

**Issue by dominota** [Tape-Worm/Gorgon#12]
Firstly, thank you so much for the Great Library.

I get problem in restore  (resize) windows after making it fullscreen. The app crashes if i exit FullScreen mode.

```
private static FormMain Initialize()
        {
            FormMain window = InitializeForm(new Size2(1920, 1080), "FX");
            try
            {
                IReadOnlyList<IGorgonVideoAdapterInfo> videoDevices = GorgonGraphics.EnumerateAdapters();
                watch.Stop();
                var elapsedMs = watch.ElapsedMilliseconds;
                if (videoDevices.Count == 0)
                {
                    throw new GorgonException(GorgonResult.CannotCreate,
                                              Gorgon requires at least a Direct3D 11.4 capable video device.\nThere is no suitable device installed on the system.");
                }
                // Find the best video device.
                _graphics = new GorgonGraphics(videoDevices.OrderByDescending(item => item.FeatureSet).First());
                _graphics = new GorgonGraphics(videoDevices[0], FeatureSet.Level_11_0);          
                _screen = new GorgonSwapChain(_graphics,
                                              window,
                                              new GorgonSwapChainInfo("Swap Chain")
                                              {
                                                  Width = 1920, 
                                                  Height = 1080,
                                                  Format = BufferFormat.R8G8B8A8_UNorm,
                                                  UseFlipMode = true
                                              });
                // Tell the graphics API that we want to render to the "screen" swap chain.
                _graphics.SetRenderTarget(_screen.RenderTargetView);
                //Set full screen
                _screen.EnterFullScreen();

                // Initialize the renderer so that we are able to draw stuff.
                _renderer = new Gorgon2D(_graphics);

                window.KeyUp += Window_KeyUp;
                window.IsLoaded = true;
                return window;
            }
            finally
            {
                EndInit();
            }
        }


private static FullScreen = true;
private static void Window_KeyUp(object sender, KeyEventArgs e)
        {
            switch (e.KeyCode)
            {
                case Keys.F1:
                    ShowStatistics = !ShowStatistics;
                    break;
                case Keys.S:

                    if (FullScreen)
                        _screen.ExitFullScreen();
                    else
                        _screen.EnterFullScreen();

                    FullScreen = !FullScreen;
                    break;
                case Keys.Escape:
                    GorgonApplication.Quit();
                    break;
            }
        }
```
``cd``
In all your examples, the window is fixed size. It seems, Gorgon does not support to change window size?. 
Please take your time to point me some hints. Thanks

- Edited to reformat code block

**Comment by Tape-Worm** [comment]
Did you get an error message when you tried to switch between modes?  If so, can you please tell me what it says?

**Comment by Tape-Worm** [comment]
I did find a bug in switching to full screen mode, but I'm not 100% convinced that it applies to your situation. Regardless, I've repaired it and I'll push up an update when I'm able.

I tried your code and I'm not seeing any issues for switching video modes.  But I suspect there's more to your code than what you've pasted here? If that's the case, I can't fully create repro for the bug, so I'll need your full code (Idle method, startup method, etc...) so I can create a test case.

**Comment by dominota** [comment]
Thank you so much! Please point me where you added a check in code before you fix it.

**Comment by Tape-Worm** [comment]
I don't need your entire project, I just need a small project to reproduce the error you're seeing.  I am currently unable to reproduce it on my side.  If I can't reproduce it, I can't fix it.

The error that you're getting is not due to the bug fix that I put in because according to the code you wrote above, you're using full screen borderless windowed mode, and according to Microsoft, the bug does not affect windowed mode, only full screen exclusive mode. So it's not likely that'll help you.

By video I'm assuming you mean files such as avi, wmv, mkv, mpg, etc... If so, then Gorgon does not support rendering video files at this time, so I'm afraid you'll have to look elsewhere for that.

**Comment by dominota** [comment]
Yes, you are right. The problem is in my code. It is not relate to your API. Thanks
