### ISSUE TITLE
Firework effect

### ISSUE THREAD

**Issue by thigiacmay** [Tape-Worm/Gorgon#14]
I love Gorgon library. Please add Firework effect in the next release. Thanks

**Comment by Tape-Worm** [comment]
This requires a particle system. Which is really outside of the scope for the library.  You should be able to create your own particle system that utilizes GorgonSprites easily enough however.  

See [http://rbwhitaker.wikidot.com/2d-particle-engine-1](http://rbwhitaker.wikidot.com/2d-particle-engine-1), this should give you a starting point. It's for XNA, but you should be able to adapt it easily enough.

**Comment by thigiacmay** [comment]
Thank you!
