### ISSUE TITLE
OnAssignDirtyItem(int, GorgonStreamOutBinding)': no suitable method found to override

### ISSUE THREAD

**Issue by dominota** [Tape-Worm/Gorgon#17]
Hi,
I got this error when building Gorgon.Graphics.Core from latest source

> OnAssignDirtyItem(int, GorgonStreamOutBinding)': no suitable method found to override

In files:
Gorgon.Graphics.Core\Pipeline\GorgonStreamOutBindings.cs
Gorgon.Graphics.Core\States\GorgonSamplerStates.cs
Gorgon.Graphics.Core\Shaders\GorgonReadWriteViewBindings.cs
Gorgon.Graphics.Core\Buffers\GorgonConstantBuffers.cs

Please have a look on it.

Thanks

**Comment by Tape-Worm** [comment]
This error is not showing up on my build server master branch, nor is it happening on my local build.  There must be something not right on your end. 

If you're using one of the other branches, then be aware there's no guarantee that they will compile and you should be using the master branch.

**Comment by dominota** [comment]
@Tape-Worm yes, your right, i fixed. Thanks
