### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Ranarrr** [Tape-Worm/Gorgon#21]
Hello, I have some issues with using 2 forms with a GorgonApplication. Got 2 questions..
Q1: Why is the field MainForm in GorgonApplication ReadOnly? Would there be a bug if it was to be set mid-program?

I have some code that I try to run, and it works, although it encounters a bug when I deactivate the graphics window (activate a different window by clicking on it).

This is the startup form:

```
Imports System.Threading
Imports Gorgon.UI

Public Class Form1
    'doing other stuff here, like normal buttons and progressbars etc...

    Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
        Dim t As New Thread(Sub()
                                Dim tmp As New Form2()

                                GorgonApplication.Run(tmp, AddressOf tmp.Idle)
                            End Sub)
        t.Start()
    End Sub
End Class
```

and the graphics form or game form:
```
Public Class Form2
    Private Sub Form2_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        Initialize()
    End Sub

    Private Sub Initialize()
        'initializing graphics and 2d interface here
    End Sub

    Public Function Idle() As Boolean
        'drawing and other things here
        Return True
    End Function
End Class
```

I can start it up, click the button in Form1, it starts up the game form, then I'd draw whatever and play the game, then exit by pressing either exit button or possibly having a button in-game, then I'd be free to start up the game with the same button in Form1.

My problem occurs the 2nd time I start up the game form. If I start it up the 2nd time, then deactivate the entire application, so not activate the startup form, but actually activating a different window (or desktop) it crashes because the first game form that was passed to GorgonApplication.Run has been disposed. (it seems to me atleast.)

Q3: I do not understand why this error is happening. Do you understand? Please explain to me.

Q4: Is there something I need to do when deactivating the window or unfocusing?

I have not seen an example where you have an already open form, then try to start a GorgonApplication.

I have attached this solution.
[WindowsApp1.zip](https://github.com/Tape-Worm/Gorgon/files/4240473/WindowsApp1.zip)

Thank you again!

**Comment by Tape-Worm** [comment]
Regarding question #1:
The main form can be reassigned if you use an ApplicationContext from System.Windows.Forms and pass it to the Run method. This application context object has a MainForm property that you can alter, and that change will be reflected in GorgonApplication.MainForm.  

GorgonApplication exposes the application context (if you provided one) via the ApplicationContext so it should be as simple as: `GorgonApplication.ApplicationContext.Main = myForm;`

**Comment by Tape-Worm** [comment]
Questions 2, 3, and 4:
This is quite odd. You're spinning up a new thread for your application message pump.  I really don't think this is going to end well (I've never tried doing this, so I have no idea what the consequences are).  

When I ran your app, I followed your directions and I got the same error. However, when I ran it a second time, and I waited about 20 seconds before re-opening the window, it worked just fine. 

What appears to be happening is that your thread isn't garbage collected when you press the button.  So it's probably in the middle of doing something, and a new application object is spun up. Since the application class is a static object (just like System.Windows.Forms.Application), it'll share the same data which the other thread is probably still using. Because of the new thread, this data has been clobbered by new data, which the other thread was not expecting, causing a race condition. I would really advise you to rethink your design here. Threads and UI stuff don't play nice together without a lot of hackery.

Also, have you tried clicking on the button when Window #2 is already open? It'll crash then too. And rightfully so, Gorgon has safety code in place to ensure you can only run one application at a time, and that you can only run it from a single thread to mitigate issues like this.

For what you're trying to accomplish, an ApplicationContext is your best bet.  You can use that to set up your form1 as the main form, and form2 can be just spun up by clicking the button like so:
```vb
Dim _formDeux as Form2 

sub button1_click(...)
{
   ' Don't allow more forms to be created until we close the 2nd form.
   button1.Enabled = false
   ' Just to be safe.
   GorgonApplication.Idle = nothing

   _form2 = new Form2()
   _form2.Show()

   ' It's been near on a decade since I last looked at Visual Basic, so I can't remember how to 
   ' set up an event.  But you'd assign the Form_Closing event for _form2 here, and have its 
   ' callback delegate re-enable your button.
   
   GorgonApplication.Idle = _form2.Idle
   ' Enable this if you want to ensure your Idle method is executed even when the window does not
   ' have focus.
   'GorgonApplication.AllowBackground = true   
}
```
No threads necessary, and perfectly stable.

**Comment by Ranarrr** [comment]
Well, I'm not able to set GorgonApplication.ApplicationContext since it's readonly, and not able to set GorgonApplication.ApplicationContext.MainForm because GorgonApplication.ApplicationContext is not set to an instance of an object.

The reason I start a new Thread is because of calling GorgonApplication.Run in my already started form causes an exception (InvalidOperationException) to be thrown. With this message: 'Starting a second message loop on a single thread is not a valid operation. Use Form.ShowDialog instead.'

So what I assume is I absolutely must have something else as a start up? Like a module (with Main function) or something that's not visible that calls GorgonApplication.Run with an ApplicationContext created from Form1? Otherwise I didn't understand your example as I can't set the IdleMethod property without any MainForm.

So I created a startup module, which has one of those 
<STAThread>
    Public Sub Main()
methods, and enables visual styles, etc, then runs form1's ApplicationContext. It works and doesn't crash, but this is gonna be hard with a splashscreen (had to do a little hacky stuff there...)

New solution:
[WindowsApp1.zip](https://github.com/Tape-Worm/Gorgon/files/4246587/WindowsApp1.zip)

This starts a splashscreen, then after 2 seconds (I guess, ish..) it closes and opens Form1.

I'd like to hear your feedback on this solution, because this solution is a bit hacky it feels, and not as smoothly done as I'd hoped for.

Thank you for your answers :)

**Comment by Tape-Worm** [comment]
You can only (as per the documentation, and, as I said in the first reply: "if you provided one") have a value on the ApplicationContext property if you provide one.  You can set the ApplicationContext by passing it in to the GorgonApplication.Run() method.  You can hook the Idle loop up at any time you like by setting the GorgonApplication.Idle property.

And yes, you must provide a Sub Main() to call GorgonApplication.Run(), using VB's built in stuff is great for whipping up line of business and other small applications quickly. However it does you no favors here, and you should avoid any "help" from Visual Basic like the plague when dealing with more complicated stuff like this. 

An application context is a class that you should inherit from.  There are sites out there that can guide on you on how to do exactly what you're looking for:
[https://www.codeproject.com/Articles/5756/Use-the-ApplicationContext-Class-to-Fully-Encapsul](https://www.codeproject.com/Articles/5756/Use-the-ApplicationContext-Class-to-Fully-Encapsul)

Your example app is close, but not quite right. You should be doing your splash and main form in your custom ApplicationContext. Look at the link provided above, it should set you on the right path.

**Comment by Ranarrr** [comment]
Thank you.
