### ISSUE TITLE
Error starting any of the examples

### ISSUE THREAD

**Issue by SteveSmith16384** [Tape-Worm/Gorgon#24]
Apologies if I've missed something obvious.  This isn't a bug, but the only other option here was "feature request".
 
**Describe the bug**
Any time I run any example, I get the error "SharpDX.SharpDXException: 'HRESULT: [0x887A0004], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_UNSUPPORTED/Unsupported], Message: The specified device interface or feature level is not supported on this system."

**To Reproduce**
1. Load solution into VS 2019, 
2. Select Sprites project (or any)
3. Press Play

**Expected behavior**
For the project to run. :)

 - OS: [e.g. Windows 10 Build 17763]
Windows 10 Pro v 1909
DirectX 12

Thanks for any help.

**Comment by Tape-Worm** [comment]
Hmm.  Judging by the message, it appears that it can't get the required interface because your drivers/hardware don't support it.

Which GPU do you have?

**Comment by SteveSmith16384** [comment]
Thanks for the quick feedback.  AFAIK I don't have any GPU; I'm just using a Dell Latitude laptop.  It does sound like the problem is caused by unsupported video.  Is there any way for me to configure it to settings my laptop does support?  I was just looking to draw some 2D sprites. :)

**Comment by Tape-Worm** [comment]
Nope, this requires a GPU that supports at least Direct3D 12.  That's how it gets its speed.

You may have D3D 12 installed, however, your integrated GPU probably doesn't support it (dxdiag will confirm this). For example, I used to have a GeForce 770 GPU and Direct 3D 12 was installed, but I could go no higher than than Direct 3D 11.1 using that GPU (at that time).

If you want to run DxDiag, you can go to the Display tab, and see the supported feature levels for your card:
![image](https://user-images.githubusercontent.com/9710137/78456499-4a610900-7661-11ea-9cae-50a15fbc4496.png)
You'll see that mine supports 12_1, 12_0, etc... I suspect yours will show 11_1, 11_0 as the maximum level.

**Comment by SteveSmith16384** [comment]
Yes, mine only goes up to 11_0.  Oh well.  Thanks for the help though. :)
