### ISSUE TITLE
Add GUI controls to graphics library

### ISSUE THREAD

**Issue by dominota** [Tape-Worm/Gorgon#27]
Dear Michael Winsor,

Could you please add some UI controls in your graphics library that can display on render screen, for example: Button, Radio Buton, Check button, Slider control...

Thank you in advance, and thank you for your great library

Best regards,

**Comment by Tape-Worm** [comment]
This is outside of the scope for Gorgon.  There are several GUI toolkits like [ImGui](https://github.com/mellinoe/ImGui.NET) that you can use (you'd need to adapt this to use with Gorgon as it won't likely work out of the box).
