### ISSUE TITLE
Can not register a device (mouse/keyboard) when my project is build in x64 mode

### ISSUE THREAD

**Issue by dominota** [Tape-Worm/Gorgon#34]
**Describe the bug**
Can not register a device (mouse, keyboard) when project is built in x64. But with AnyCpu mode, my project can run fine.

**To Reproduce**
1. What did you do?

```
public partial class Form1 : Form
    {
        GorgonRawInput input;
        GorgonRawMouse mouse;
        GorgonRawKeyboard keyboard;
        public Form1()
        {
            InitializeComponent();

            input = new GorgonRawInput(this);
            mouse = new GorgonRawMouse();
            input.RegisterDevice(mouse);

        }
    }
```
**Expected behavior**
I need build my project in X64

**Screenshots**
![ErrorInput](https://user-images.githubusercontent.com/54459455/86554624-5cac5500-bf78-11ea-87dc-156c95b40dc9.png)

 - OS: Windows 10 x64 build 18362.900
 - Version 1903
- Visual Studio 2017

**Additional context**
None

**Comment by Tape-Worm** [comment]
I cannot reproduce this on my end. 

AnyCPU should automatically use x64 instructions if your OS and machine are x64, so switching to x64 explicitly shouldn't be causing any problems as it's essentially the same (ensure you have Prefer 32 bit unchecked in your project properties).

The only thing I can recommend is moving your code from the constructor to the Form_Load event.  You really shouldn't be putting heavy duty code like raw input in your constructor anyway.

**Comment by dominota** [comment]
Thank you,
I changed the code (like in this link (1.2MB)) but i did not get success.
[https://mega.nz/file/abpxxJjK#y0HQbvzJtTzeiOOPOJI0vIVFIf0hvbuM8yre1_Af3Lc](url)

The version of graphics library is Gorgon_3.0.96.088.zip from this link: [https://github.com/Tape-Worm/Gorgon/releases/download/v3.0.96.088/Gorgon_3.0.96.088.zip](url)

Can you have a look on it?

Thanks

**Comment by Tape-Worm** [comment]
I ran it, and it worked fine for me.  

Can you describe your hardware setup?  It's entirely possible that some device on your system is causing some unexpected behaviour.

**Comment by dominota** [comment]
if I directly use SharpDX.DirectInput then it works:

`SharpDX.DirectInput.DirectInput mInput = new SharpDX.DirectInput.DirectInput();
SharpDX.DirectInput.Keyboard mKeyboard;
mKeyboard = new SharpDX.DirectInput.Keyboard(mInput);
mKeyboard.Acquire();

...
KeyboardState ks = mKeyboard.GetCurrentState();
`

My computer: Dell Intel Core i7-4700
Graphics card:NVIDIA Gefore GT 1030
Keyboard (usb): Lenovo LXH-EKB-10YA
Mouse(usb): Logitech 100Mr

**Comment by Tape-Worm** [comment]
DirectInput is not RawInput. They're quite different.  But if it works for you, then that's great.

The hardware looks normal enough to me. Unfortunately, without knowing what data is being returned from the Win32 RawInput API on your system (particularly in x64), I can't really say why it won't work for you.  

You could try using the [debug version of Gorgon's assemblies](https://github.com/Tape-Worm/Gorgon/releases/download/v3.0.96.088/Gorgon_Debug_3.0.96.088.zip) and capture the detailed version of the exception information.

**Comment by dominota** [comment]
Thanks @Tape-Worm , still the same error. 
i will use Input from SharpDX
