### ISSUE TITLE
Can not override WndProc function

### ISSUE THREAD

**Issue by dominota** [Tape-Worm/Gorgon#35]
**Describe the bug**
I implement to override the WndProc of Form that i used to render with Gorgon library but i can not do. It throws an error  "Error creating window handle."

**To Reproduce**
1. What did you do?
`protected override void WndProc(ref System.Windows.Forms.Message m)
         {
             // respond to messages here
         }`
If i remove such function, then my project just works fine
**Expected behavior**
I want to override this function to handle WM_CHAR... events
**Screenshots**

    OS: Windows 10 x64 build 18362.900
    Version 1903
    Visual Studio 2017

**Additional context**

**Comment by Tape-Worm** [comment]
This has nothing to do with Gorgon. Please take such questions to [gamedev.net](https://www.gamedev.net).
